Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
    #- Type: LocalFile
    #  LocalFile: ./definitions/definition-for-aws-icons-light.yaml

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - VPC
    # VPC
    VPC:
      Type: AWS::EC2::VPC
      Direction: horizontal
      Children:
        - VPCAvailabilityZone1A
        - VPCAvailabilityZone2B
      BorderChildren:
        - Position: S
          Resource: IGW
    VPCAvailabilityZone1A:
      Type: AWS::EC2::AvailabilityZone
      Direction: vertical
      Title: us-west-1a
      Children:
        - VPCPrivateDBSubnet1A
        - VPCPrivateAppSubnet1A
        - VPCPrivateNFWSubnet1A
        - VPCPublicSubnet1A
    VPCAvailabilityZone2B:
      Type: AWS::EC2::AvailabilityZone
      Direction: vertical
      Title: us-west-2b
      Children:
        - VPCPrivateDBSubnet2B
        - VPCPrivateAppSubnet2B
        - VPCPrivateNFWSubnet2B
        - VPCPublicSubnet2B
    VPCPublicSubnet1A:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - NLB1A
    NLB1A:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: Network Load Balancer
    VPCPublicSubnet2B:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - NLB2B
    NLB2B:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: Network Load Balancer
    VPCPrivateAppSubnet1A:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateAppSubnet1AEKS
    VPCPrivateAppSubnet1AEKS:
      Type: AWS::EKS
    VPCPrivateAppSubnet2B:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateAppSubnet2BEKS
    VPCPrivateAppSubnet2BEKS:
      Type: AWS::EKS
    VPCPrivateNFWSubnet1A:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateNFWSubnet1AInstance
    VPCPrivateNFWSubnet1AInstance:
      Type: AWS::NetworkFirewall::Firewall
    VPCPrivateNFWSubnet2B:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateNFWSubnet2BInstance
    VPCPrivateNFWSubnet2BInstance:
      Type: AWS::NetworkFirewall::Firewall
    VPCPrivateDBSubnet1A:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateDBSubnet1AInstance
    VPCPrivateDBSubnet1AInstance:
      Type: AWS::RDS::DBInstance
    VPCPrivateDBSubnet2B:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPCPrivateDBSubnet2BInstance
    VPCPrivateDBSubnet2BInstance:
      Type: AWS::RDS::DBInstance
    IGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect
    User:
      Type: AWS::Diagram::Resource
      Preset: User

  Links:
    - Source: NLB1A
      SourcePosition: N
      Target: VPCPrivateNFWSubnet1AInstance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: NLB2B
      SourcePosition: N
      Target: VPCPrivateNFWSubnet2BInstance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: VPCPrivateNFWSubnet1AInstance
      SourcePosition: N
      Target: VPCPrivateAppSubnet1AEKS
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: VPCPrivateNFWSubnet2BInstance
      SourcePosition: N
      Target: VPCPrivateAppSubnet2BEKS
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: VPCPrivateAppSubnet1AEKS
      SourcePosition: N
      Target: VPCPrivateDBSubnet1AInstance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: VPCPrivateAppSubnet2BEKS
      SourcePosition: N
      Target: VPCPrivateDBSubnet2BInstance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: IGW
      SourcePosition: N
      Target: NLB1A
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: IGW
      SourcePosition: N
      Target: NLB2B
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: User
      SourcePosition: N
      Target: IGW
      TargetPosition: S
      TargetArrowHead:
        Type: Open
